CREATE TABLE IF NOT EXISTS `Patient` (
	`Patient_id` INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	`First_Name` TEXT NOT NULL,
	`Last_Name` TEXT NOT NULL,
	`Date_Of_Birth` REAL NOT NULL,
	`Gender` INTEGER NOT NULL,
	`Blood_Type` TEXT NOT NULL,
	`Phone` TEXT NOT NULL,
	`Email` TEXT NOT NULL,
	`Address` TEXT NOT NULL,
	`City` TEXT NOT NULL,
	`Postcode` INTEGER NOT NULL,
	`Doctor` TEXT NOT NULL,
	`Insurance` TEXT NOT NULL,
	`Allergies` TEXT NOT NULL,
	`Notes` TEXT NOT NULL,
	`Em_name` TEXT NOT NULL,
	`Em_relation` TEXT NOT NULL,
	`Em_phone` TEXT NOT NULL,
	FOREIGN KEY (`Doctor`) REFERENCES `Doctor`(`Doctor_id`)
);
CREATE TABLE IF NOT EXISTS `Appointment` (
	`Appointment_id` INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	`Patient_id` INTEGER NOT NULL,
	`Status` INTEGER NOT NULL,
	`Priority` INTEGER NOT NULL,
	`Doctor` TEXT NOT NULL,
	`Department` INTEGER NOT NULL,
	`Appointment_type` INTEGER NOT NULL,
	`Duration` INTEGER NOT NULL,
	`Date` INTEGER NOT NULL,
	`Time` INTEGER NOT NULL,
	`Time_end` INTEGER NOT NULL,
	`Reason` INTEGER NOT NULL,
	`Notes` INTEGER NOT NULL,
	FOREIGN KEY (`Patient_id`) REFERENCES `Patient`(`Patient_id`),
	FOREIGN KEY (`Doctor`) REFERENCES `Doctor`(`Doctor_id`)
);